services:
  - type: web
    name: ddvs-backend
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
      - key: DATABASE_USERNAME
        value: postgres.xsanffkcnpcilvuvfrif
      - key: DATABASE_PASSWORD
        value: Plutoski@88
      - key: JWT_SECRET
        value: ddvs-super-secret-jwt-key-2026-production