spring.application.name=ddvs

# DB
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db.xsanffkonpcilvuvfrif.supabase.co:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Plutoski@88}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:ddvs-super-secret-jwt-key-2026-production}
jwt.expiration=86400000